Replace unicode literals with numeric values in tests
Replace unicode character and string literals because MSVC is
unable to compile such a code and will produce error C2015
(too many characters in constant).